name: CPP Azure FunctionApp Deployment
trigger: none
pr:
- main

parameters:
- name: environment
- name: functionapp
  displayName: The name of the application
  default: notifyatt
- name: tfversion
  default: 1.3.1
- name: agentPool
  values:
  - "MDV-ADO-AGENTS-01"
  - "MPD-ADO-AGENTS-01"
  default: "MDV-ADO-AGENTS-01"
- name: platform
  values:
  - nonlive
  - live
  default: nonlive

variables:
- template: azure-pipeline-variables/${{ parameters.platform }}.yml

resources:
  repositories:
  - repository: cppAzureDevOpsTemplates
    type: github
    name: hmcts/cpp-azure-devops-templates
    ref: 'main'
    endpoint: 'cpp-apps'

stages:
  - stage: precommit
    pool:
      name: ${{ parameters.agentPool }}
    jobs:
    - job: precommit
      steps:
      - template: steps/terraform/terraform-precommit.yaml@cppAzureDevOpsTemplates
        parameters:
          tfversion: ${{ parameters.tfversion }}


  - ${{ if eq(variables['Build.Reason'], 'Manual') }}:
    - template: pipelines/terraform-ws-plan-and-apply.yaml@cppAzureDevOpsTemplates
      parameters:
        tfversion: ${{ parameters.tfversion }}
        azureServiceConnection: ${{ variables.azureServiceConnection }}
        spnCredentialsVarGroup: ${{ variables.spnCredentialsVarGroup }}
        vaultAdminCredentialsVarGroup: ${{ variables.vaultAdminCredentialsVarGroup }}
        platform: ${{ parameters.platform }}
        environment: ${{ parameters.environment }}
        tfvars: ${{ parameters.functionapp }}
        serviceName: ${{ parameters.functionapp }}
        agentPool: ${{ parameters.agentPool }}
