name: CPP Azure FunctionApp Deployment
trigger: none
pr:
- main

parameters:
- name: environment
  displayName: Environment and Terraform Workspace
  type: string
  default: dev
  values:
  - dev
  - sit
  - nft
  - prp
  - prx
  - prd
- name: spnCredentialsVarGroup
  default: "terratest-app-registration"
- name: azureServiceConnection
  default: "ado_nonlive_service_principal_lab"
- name: tfversion
  default: 1.2.3
- name: agentPool
  default: "ubuntu-latest"

resources:
  repositories:
  - repository: cppAzureDevOpsTemplates
    type: github
    name: hmcts/cpp-azure-devops-templates
    endpoint: 'cpp-apps'

stages:
  - stage: precommit
    jobs:
    - job: pre
      pool:
        vmImage: ${{ parameters.agentPool }}
      steps:
        - task: CopyFiles@1
          displayName: Copy Terraform Files
          inputs:
            TargetFolder: ${Build.ArtifcatStagingDirectory}
            cleanTargetFolder: true
        - template: steps/common/precommit.yaml@cppAzureDevOpsTemplates
          parameters:
            tfversion: ${{ parameters.tfversion }}
